# Generated by Django 5.1.7 on 2025-03-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='roll_no',
            new_name='roll_number',
        ),
    ]
